'' ------------------------------------------------------------------------------
''  <auto-generated>
''    Generated by Xsd2Code. Version 3.4.0.32989
''    <NameSpace>FilterElements.vb</NameSpace><Collection>List</Collection><codeType>VisualBasic</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
''  </auto-generated>
'' ------------------------------------------------------------------------------
Imports System
Imports System.Diagnostics
Imports System.Xml.Serialization
Imports System.Collections
Imports System.Xml.Schema
Imports System.ComponentModel
Imports System.IO
Imports System.Text
Imports System.Collections.Generic

Namespace FilterElements.vb
    
    #Region "Base entity class"
    Partial Public Class EntityBase(Of T)
        
        Private Shared sSerializer As System.Xml.Serialization.XmlSerializer
        
        Private Shared ReadOnly Property Serializer() As System.Xml.Serialization.XmlSerializer
            Get
                If (sSerializer Is Nothing) Then
                    sSerializer = New System.Xml.Serialization.XmlSerializer(GetType(T))
                End If
                Return sSerializer
            End Get
        End Property
        
        #Region "Serialize/Deserialize"
        '''<summary>
        '''Serializes current EntityBase object into an XML document
        '''</summary>
        '''<returns>string XML value</returns>
        Public Overridable Function Serialize() As String
            Dim streamReader As System.IO.StreamReader = Nothing
            Dim memoryStream As System.IO.MemoryStream = Nothing
            Try 
                memoryStream = New System.IO.MemoryStream
                Serializer.Serialize(memoryStream, Me)
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin)
                streamReader = New System.IO.StreamReader(memoryStream)
                Return streamReader.ReadToEnd
            Finally
                If (Not (streamReader) Is Nothing) Then
                    streamReader.Dispose
                End If
                If (Not (memoryStream) Is Nothing) Then
                    memoryStream.Dispose
                End If
            End Try
        End Function
        
        '''<summary>
        '''Deserializes workflow markup into an EntityBase object
        '''</summary>
        '''<param name="xml">string workflow markup to deserialize</param>
        '''<param name="obj">Output EntityBase object</param>
        '''<param name="exception">output Exception value if deserialize failed</param>
        '''<returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        Public Overloads Shared Function Deserialize(ByVal xml As String, ByRef obj As T, ByRef exception As System.Exception) As Boolean
            exception = Nothing
            obj = CType(Nothing, T)
            Try 
                obj = Deserialize(xml)
                Return true
            Catch ex As System.Exception
                exception = ex
                Return false
            End Try
        End Function
        
        Public Overloads Shared Function Deserialize(ByVal xml As String, ByRef obj As T) As Boolean
            Dim exception As System.Exception = Nothing
            Return Deserialize(xml, obj, exception)
        End Function
        
        Public Overloads Shared Function Deserialize(ByVal xml As String) As T
            Dim stringReader As System.IO.StringReader = Nothing
            Try 
                stringReader = New System.IO.StringReader(xml)
                Return CType(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader)),T)
            Finally
                If (Not (stringReader) Is Nothing) Then
                    stringReader.Dispose
                End If
            End Try
        End Function
        
        '''<summary>
        '''Serializes current EntityBase object into file
        '''</summary>
        '''<param name="fileName">full path of outupt xml file</param>
        '''<param name="exception">output Exception value if failed</param>
        '''<returns>true if can serialize and save into file; otherwise, false</returns>
        Public Overloads Overridable Function SaveToFile(ByVal fileName As String, ByRef exception As System.Exception) As Boolean
            exception = Nothing
            Try 
                SaveToFile(fileName)
                Return true
            Catch e As System.Exception
                exception = e
                Return false
            End Try
        End Function
        
        Public Overloads Overridable Sub SaveToFile(ByVal fileName As String)
            Dim streamWriter As System.IO.StreamWriter = Nothing
            Try 
                Dim xmlString As String = Serialize
                Dim xmlFile As System.IO.FileInfo = New System.IO.FileInfo(fileName)
                streamWriter = xmlFile.CreateText
                streamWriter.WriteLine(xmlString)
                streamWriter.Close
            Finally
                If (Not (streamWriter) Is Nothing) Then
                    streamWriter.Dispose
                End If
            End Try
        End Sub
        
        '''<summary>
        '''Deserializes xml markup from file into an EntityBase object
        '''</summary>
        '''<param name="fileName">string xml file to load and deserialize</param>
        '''<param name="obj">Output EntityBase object</param>
        '''<param name="exception">output Exception value if deserialize failed</param>
        '''<returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        Public Overloads Shared Function LoadFromFile(ByVal fileName As String, ByRef obj As T, ByRef exception As System.Exception) As Boolean
            exception = Nothing
            obj = CType(Nothing, T)
            Try 
                obj = LoadFromFile(fileName)
                Return true
            Catch ex As System.Exception
                exception = ex
                Return false
            End Try
        End Function
        
        Public Overloads Shared Function LoadFromFile(ByVal fileName As String, ByRef obj As T) As Boolean
            Dim exception As System.Exception = Nothing
            Return LoadFromFile(fileName, obj, exception)
        End Function
        
        Public Overloads Shared Function LoadFromFile(ByVal fileName As String) As T
            Dim file As System.IO.FileStream = Nothing
            Dim sr As System.IO.StreamReader = Nothing
            Try 
                file = New System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read)
                sr = New System.IO.StreamReader(file)
                Dim xmlString As String = sr.ReadToEnd
                sr.Close
                file.Close
                Return Deserialize(xmlString)
            Finally
                If (Not (file) Is Nothing) Then
                    file.Dispose
                End If
                If (Not (sr) Is Nothing) Then
                    sr.Dispose
                End If
            End Try
        End Function
        #End Region
    End Class
    #End Region
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/FilterElements.xsd"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/FilterElements.xsd", IsNullable:=false)>  _
    Partial Public Class StandardElements
        Inherits EntityBase(Of StandardElements)
        
        Private filterElementField As List(Of FilterElementType)
        
        '''<summary>
        '''StandardElements class constructor
        '''</summary>
        Public Sub New()
            MyBase.New
            Me.filterElementField = New List(Of FilterElementType)
        End Sub
        
        <System.Xml.Serialization.XmlElementAttribute("FilterElement")>  _
        Public Property FilterElement() As List(Of FilterElementType)
            Get
                Return Me.filterElementField
            End Get
            Set
                Me.filterElementField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/FilterElements.xsd"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/FilterElements.xsd", IsNullable:=true)>  _
    Partial Public Class FilterElementType
        Inherits EntityBase(Of FilterElementType)
        
        Private assemblyFilenameField As String
        
        Private elementIDField As String
        
        Private parentModuleIDField As String
        
        Private elementIsDisabledField As Boolean
        
        Private elementBracingLeftFrontField As Boolean
        
        Private elementBracingLeftFrontFieldSpecified As Boolean
        
        Private elementBracingLeftRearField As Boolean
        
        Private elementBracingLeftRearFieldSpecified As Boolean
        
        Private elementBracingRightFrontField As Boolean
        
        Private elementBracingRightFrontFieldSpecified As Boolean
        
        Private elementBracingRightRearField As Boolean
        
        Private elementBracingRightRearFieldSpecified As Boolean

        Private elementNumFiltersWidthField As String

        Public Sub New()
            MyBase.New
            Me.assemblyFilenameField = "Something.iam"
            Me.elementIsDisabledField = False
        End Sub

        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute("Something.iam")>
        Public Property AssemblyFilename() As String
            Get
                Return Me.assemblyFilenameField
            End Get
            Set
                Me.assemblyFilenameField = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property ElementID() As String
            Get
                Return Me.elementIDField
            End Get
            Set
                Me.elementIDField = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property ParentModuleID() As String
            Get
                Return Me.parentModuleIDField
            End Get
            Set
                Me.parentModuleIDField = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlAttributeAttribute(),
         System.ComponentModel.DefaultValueAttribute(False)>
        Public Property ElementIsDisabled() As Boolean
            Get
                Return Me.elementIsDisabledField
            End Get
            Set
                Me.elementIsDisabledField = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property ElementBracingLeftFront() As Boolean
            Get
                Return Me.elementBracingLeftFrontField
            End Get
            Set
                Me.elementBracingLeftFrontField = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ElementBracingLeftFrontSpecified() As Boolean
            Get
                Return Me.elementBracingLeftFrontFieldSpecified
            End Get
            Set
                Me.elementBracingLeftFrontFieldSpecified = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property ElementBracingLeftRear() As Boolean
            Get
                Return Me.elementBracingLeftRearField
            End Get
            Set
                Me.elementBracingLeftRearField = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ElementBracingLeftRearSpecified() As Boolean
            Get
                Return Me.elementBracingLeftRearFieldSpecified
            End Get
            Set
                Me.elementBracingLeftRearFieldSpecified = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property ElementBracingRightFront() As Boolean
            Get
                Return Me.elementBracingRightFrontField
            End Get
            Set
                Me.elementBracingRightFrontField = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ElementBracingRightFrontSpecified() As Boolean
            Get
                Return Me.elementBracingRightFrontFieldSpecified
            End Get
            Set
                Me.elementBracingRightFrontFieldSpecified = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property ElementBracingRightRear() As Boolean
            Get
                Return Me.elementBracingRightRearField
            End Get
            Set
                Me.elementBracingRightRearField = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ElementBracingRightRearSpecified() As Boolean
            Get
                Return Me.elementBracingRightRearFieldSpecified
            End Get
            Set
                Me.elementBracingRightRearFieldSpecified = Value
            End Set
        End Property

        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>
        Public Property ElementNumFiltersWidth() As String
            Get
                Return Me.elementNumFiltersWidthField
            End Get
            Set
                Me.elementNumFiltersWidthField = Value
            End Set
        End Property
    End Class
End Namespace
